### ISSUE TITLE
Running phoenix on a i386 architecture

### ISSUE THREAD

**Issue by padmaJS** [phoenix-by-example/greeter#4]
I am using a i386 laptop trying to run phoenix following this repo
But when I do 
`cd todo`
`mix phx.server`
I get this following
`[info] Running TodoWeb.Endpoint with cowboy 2.9.0 at 127.0.0.1:4000 (http)`
`[info] Access TodoWeb.Endpoint at http://localhost:4000`
`[error] Task #PID<0.459.0> started from TodoWeb.Endpoint terminating`
`** (RuntimeError) could not download esbuild for architecture: i686-pc-linux-gnu`
`    (esbuild 0.3.3) lib/esbuild.ex:236: Esbuild.target/0`
`    (esbuild 0.3.3) lib/esbuild.ex:198: Esbuild.install/0`
`    (esbuild 0.3.3) lib/esbuild.ex:183: Esbuild.install_and_run/2`
`    (phoenix 1.6.2) lib/phoenix/endpoint/watcher.ex:19: Phoenix.Endpoint.Watcher.watch/2`
`    (elixir 1.12.2) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2`
`    (stdlib 3.15.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3`
`Function: &Phoenix.Endpoint.Watcher.watch/2`
`    Args: ["esbuild", {Esbuild, :install_and_run, [:default, ["--sourcemap=inline", "--watch"]]}]`

This keeps spawning new process with same error in an endless loop

But the localhost:4000/ works though

**Comment by zorn** [comment]
@padmaJS So sorry you are running into trouble. Not sure I have THE answer for you but I can try to explain what I see.

With Phoenix 1.6 the default new project template now uses [esbuild](https://esbuild.github.io/) over the previous webpack asset bundler. `esbuild` is written in go and has many complied versions available for download and the thought is it will be more reliable long term for people over webpack. 

For you sadly, this has not resulted in the seamless experience the Phoenix team is shooting for. It appears a complied version for your combination of computer/cpu is not available. [The list of known builds is here.](https://esbuild.github.io/getting-started/#download-a-build)

I believe the solution for you would be to install `esbuild` yourself, probably via `npm` 

<https://esbuild.github.io/getting-started/#install-esbuild> 

and then configure a manual `esbuild` path as described in the docs: 

<https://hexdocs.pm/esbuild/Esbuild.html#module-esbuild-configuration>

In the `greeter` project it would be around this file:

https://github.com/elixirfocus/greeter/blob/669692ca9bb4cddd43a33e47cb7fc78972976a28/config/config.exs#L29-L36

Hope this info helps. Let me know if you have any follow up questions.
